Pull more versions with release notes from github releases
tighten/laravelversions pull request #14
Opened 2021-01-26 17:50 UTC by dariusj18

2021-01-26 18:19 UTC, dariusj18 commented
I didn't touch the API side, I was mainly doing this because I saw an opportunity to add some extra information.

2021-01-26 23:20 UTC, mattstauffer commented
I love this! I've been wanting to re-work it to add a DB entry for every release, like we do with Checkmate (https://github.com/tighten/checkmate), but you just got ahead of it for me, parsed the description, *and* added the concept of `is_front`!

Thank you!

I'll need to work on this, or you can, so we can add some tests to make sure that non `is_front` versions don't show up in the wrong places, and the checks that show some things on `/5.1.1` type routes but not on `/5` routes still work correctly, but we really needed those tests anyway. Also will have to check and test the API to make sure this didn't break it--i assume it'll need some scoping down before this can be merged.

Feel free to make any updates you want based on this paragraph above; i'll also try to find some time to work through it and implement some of these changes if i can.

Again, thanks!

2023-04-25 14:06 UTC, faxblaster commented on README.md
> +1. Create a [GitHub Personal Access Token](https://github.com/settings/tokens) and update the  `GITHUB_TOKEN` key in your `.env` file.
Not sure if it's worth noting here, but you have to use a "classic" PAT for GraphQL queries. I tested first with a fine-grained token, but looks like [the github cli hasn't been updated to support them yet](https://github.com/cli/cli/issues/6680). 🙃

2023-04-25 17:23 UTC, faxblaster requested changes
Added a quick note for merging, but this is so nice! I especially like the new `version->order` concept for speed, rather than ordering on multiple attributes. And the tests are especially nice and readable. 🚀

2023-04-26 18:26 UTC, merged

2023-04-26 18:27 UTC, driftingly commented
Thanks @dariusj18 for getting this started!  Sorry it sat for so long!