Feature/translation issues#19
tighten/laravelversions pull request #22
Opened 2021-02-09 19:43 UTC by olsza

Hay, adds a branch where you can add translations + display language flags, once configured.
Contains and does not include:
- [x] EN translation pattern
- [x] full Polish translation
- [ ] Instrukacja how to add a new translation
- [ ] translating month names with date ->format('F Y')

ps. you have to remember to run ``` npm install && npm run prod ``` to download graphic flags
I didn't commit graphic flags and css styles in the public directory, because the above commands will do that

2021-02-10 09:47 UTC, olsza commented
the end result, i.e. the view, can be seen here https://github.com/tighten/laravelversions/issues/19#issuecomment-776582522

2021-02-15 02:46 UTC, mattstauffer requested changes
Great work!

A few notes attached below.

And, I remember that with Onramp, it was hard to choose flags because some languages (e.g. English, Spanish) are attached to more than one country and so the flag isn't the best icon. Could you update that dropdown to instead use the language name, like we did on Onramp?

Thanks so much! Really great work here!

2021-02-15 02:46 UTC, mattstauffer commented on resources/views/includes/langs.blade.php
> +            <a hreflang="{{ $lang }}" href="{{ \Route::localizedUrl($lang) }}" title="{{ $lang }}">
```suggestion
            <a hreflang="{{ $lang }}" href="{{ Route::localizedUrl($lang) }}" title="{{ $lang }}">
```

2021-02-15 02:46 UTC, mattstauffer commented on resources/views/includes/meta-langs.blade.php
> +    <link rel="alternate" hreflang="{{ $lang }}" href="{{ \Route::localizedUrl($lang) }}" />
```suggestion
    <link rel="alternate" hreflang="{{ $lang }}" href="{{ Route::localizedUrl($lang) }}" />
```

2021-02-15 02:46 UTC, mattstauffer commented on resources/views/layouts/app.blade.php
> +        <title>{{ $title ? $title . ' - ' : '' }}{{ __('Laravel Version') }}</title>
```suggestion
        <title>{{ $title ? $title . ' - ' : '' }}{{ __('Laravel Versions') }}</title>
```

2021-02-15 02:46 UTC, mattstauffer commented on resources/views/layouts/app.blade.php
> +                @if ( ! App::isLocale( Config::get('localized-routes.omit_url_prefix_for_locale') ) )
```suggestion
                @if (! App::isLocale(Config::get('localized-routes.omit_url_prefix_for_locale')))
```

2021-02-15 10:08 UTC, olsza commented
ok @mattstauffer, I know that.
Or maybe not to include, for example, in the configuration of language names, simply give the country code?
However, do you use the full names of the languages?

2021-02-15 15:23 UTC, mattstauffer commented
<img width="303" alt="image" src="https://user-images.githubusercontent.com/151829/107964864-c4e40000-6f77-11eb-8ca2-b86b08e5a1cf.png">

^^ This is Onramp.

2021-02-15 15:23 UTC, mattstauffer commented
But in the configuration, we keep it with just the code:

https://github.com/tighten/onramp/tree/main/resources/lang

2021-02-15 23:15 UTC, olsza commented
new view of language menu:

![Zrzut ekranu z 2021-02-16 00-10-58](https://user-images.githubusercontent.com/12556170/108001151-fdbdbc80-6feb-11eb-9739-279f42b78aab.png)
![Zrzut ekranu z 2021-02-16 00-06-16](https://user-images.githubusercontent.com/12556170/108001153-feeee980-6feb-11eb-97e2-a4d37b48dda7.png)

2021-02-17 17:39 UTC, olsza commented
I fixed style menu languages
FireFox on the left, to the right of Chrome

![Zrzut ekranu z 2021-02-17 18-28-25](https://user-images.githubusercontent.com/12556170/108244117-201c1b00-714f-11eb-9439-6ebb5290abe7.png)

2021-02-20 02:11 UTC, mattstauffer commented
Thanks for the update! I've been out of office with my family all week, but I'm taking a look now.

2021-02-20 02:12 UTC, merged

2021-02-20 02:12 UTC, mattstauffer commented
Thanks for your hard work on this @olsza!