Feature/add estimated in table
tighten/laravelversions pull request #46
Opened 2021-03-01 18:25 UTC by olsza

I corrected the use of long and short dates for future versions.
I added on "estimated" dates

Now:
![now-lv](https://user-images.githubusercontent.com/12556170/109541203-d4a92b80-7ac3-11eb-9915-e6b7cdc41855.png)

My propozytion:
![propozytion-lv](https://user-images.githubusercontent.com/12556170/109541245-e1c61a80-7ac3-11eb-9c7c-668e71ba3062.png)

2021-03-02 04:17 UTC, mattstauffer requested changes
Good work! A few small notes.

2021-03-02 04:17 UTC, mattstauffer commented on resources/views/partials/tables/current_table.blade.php
> +                                {{
I'd rather keep this one a single line please

2021-03-02 04:17 UTC, mattstauffer commented on resources/views/partials/tables/current_table.blade.php
> +                                        $version->released_at->gt(now())
Could you indent the second and third line of all of the instances where you changed the syntax like this?

2021-03-02 12:04 UTC, olsza commented
I understand wherever I did some lines (good practice) to change back to single line?
If so, no problem ;)
I am asking because I do not know if this applies to all recent changes or only to the two that you marked.

2021-03-03 12:25 UTC, olsza commented
ok, corrected :)

2021-03-03 15:29 UTC, mattstauffer commented
Thanks for the updates!

2021-03-03 15:29 UTC, merged